[package]
name = "dhtm_core"
version = "0.1.0"
authors = ["johker <johannes.kern@zoho.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
zmq = "0.9.2"
htm = { path = "../dhtm_lib" }
time = "0.2.25"
